#> Docker image build arguments:
FROM almalinux:9.4

ARG VERSION=3.14.4
ARG S6_OVERLAY_VERSION=3.2.2.0

LABEL fts-version=${VERSION}

#> Enable CRB repo
COPY almalinux-crb.repo /etc/yum.repos.d/almalinux-crb.repo

#> Update image
#> Install EL9 dependencies
RUN dnf update -y && \
    dnf install -y epel-release && \
    dnf clean all

#> Add supported Alma9 repos
ADD http://fts-repo.web.cern.ch/fts-repo/fts3-el9.repo \
    http://fts-repo.web.cern.ch/fts-repo/fts3-depend.repo \
    /etc/yum.repos.d

# Install OSG Repo
RUN dnf install -y https://repo.osg-htc.org/osg/25-main/osg-25-main-el9-release-latest.rpm 

#> Install the FTS packages and dependencies
#> Install FTS
#> Install utils
RUN dnf install -y \
    gfal2-plugin-mock gfal2-all \
    gettext cronie crontabs fetch-crl \
    fts-server-${VERSION} \
    fts-server-selinux-${VERSION} \
    fts-mysql-${VERSION} \
    fts-activemq-${VERSION} \
    vo-client \
    procps which \
    # Install mariadb
    mariadb && \
    dnf clean all && \
    rm -rf /var/cache/dnf

#> Install s6-overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz \
    https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz \
    /tmp

RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
RUN rm -rf /tmp/s6-overlay-*.tar.xz

#> Grant group write access
RUN chmod -R 775 /etc/grid-security \
    /etc/httpd /run/httpd /var/log/httpd \
    /var/lib/fts3 /var/log/fts3 /var/lib/fts3

#> Grant group read access
RUN chmod 664 /etc/fts3/*
RUN chmod 775 /run /etc/fts3
RUN chmod g=u /etc/passwd

#> Copy rootfs to /
COPY rootfs/ /

#> Add lancaster vomses
RUN echo '"lsst" "voms.hec.lancs.ac.uk" "15003" "/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=voms.hec.lancs.ac.uk" "lsst"' >> /etc/vomses

#> Add setup script
RUN chmod +x /tmp/setup.sh

#> Ensure all run scripts are executable
RUN chmod +x /etc/s6-overlay/s6-rc.d/*/run
RUN chmod +x /etc/s6-overlay/s6-rc.d/*/up
RUN chmod 0777 /tmp

ENTRYPOINT ["/init"]
