#> Docker image build arguments:
FROM almalinux:9.8

ARG IMAGE_VERSION=dev
ARG S6_OVERLAY_VERSION=3.2.2.0

LABEL fts-version=3.14.4 \
      image-version=${IMAGE_VERSION} \
      description="FTS3 Monitoring Container" \
      maintainer="Dennis Lee <dylee@fnal.gov>" \
      fts_serveer_version="3.14.4" \
      fts_mysql_version="3.14.4"

#> Enable CRB repo
COPY almalinux-crb.repo /etc/yum.repos.d/almalinux-crb.repo

#> Add supported Alma9 repos
ADD http://fts-repo.web.cern.ch/fts-repo/fts3-el9.repo \
    http://fts-repo.web.cern.ch/fts-repo/fts3-depend.repo \
    /etc/yum.repos.d

#> Update image
#> Install EL9 dependencies
RUN <<EOF
dnf update -y
dnf install -y epel-release
# Install OSG Repo
dnf install -y https://repo.osg-htc.org/osg/25-main/osg-25-main-el9-release-latest.rpm
dnf clean all
rm -rf /var/cache/dnf
EOF

#> Install the FTS packages and dependencies
#> Install FTS
#> Install utils
RUN <<EOF
dnf install -y \
gfal2-plugin-mock gfal2-all \
gettext cronie crontabs fetch-crl \
fts-server-3.14.4 \
fts-server-selinux-3.14.4 \
fts-mysql-3.14.4 \
vo-client \
procps which \
mariadb
dnf clean all
rm -rf /var/cache/dnf

#> Set fts3 gid, uid
groupmod -g 2000 fts3 2>/dev/null || true
usermod -u 1000 -g 2000 fts3 2>/dev/null || true

EOF

WORKDIR /tmp

#> Install s6-overlay
RUN <<EOF
curl -LO https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
curl -LO https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz
tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
rm -rf /tmp/s6-overlay-*.tar.xz
EOF

#> Copy rootfs to /
COPY rootfs/ /

#> Grant group write access
RUN <<EOF
chmod -R 775 /etc/grid-security \
/etc/httpd /run/httpd /var/log/httpd \
/var/lib/fts3 /var/log/fts3 /var/lib/fts3

#> Grant group read access
chmod 664 /etc/fts3/*
chmod 775 /run /etc/fts3
chmod g=u /etc/passwd

#> Ensure all run scripts are executable
chmod +x /tmp/setup.sh
chmod +x /etc/s6-overlay/s6-rc.d/*/run
chmod +x /etc/s6-overlay/s6-rc.d/*/up
chmod 0777 /tmp
EOF

#> Add lancaster vomses
RUN echo '"lsst" "voms.hec.lancs.ac.uk" "15003" "/C=UK/O=eScience/OU=Lancaster/L=Physics/CN=voms.hec.lancs.ac.uk" "lsst"' >> /etc/vomses

ENTRYPOINT ["/init"]
