#> Docker image build arguments:
FROM almalinux:9.8

ARG IMAGE_VERSION=dev
ARG S6_OVERLAY_VERSION=3.2.2.0

LABEL fts-version="3.14.3" \
      image-version="${IMAGE_VERSION}" \
      description="FTS3 Rest Container" \
      maintainer="Dennis Lee <dylee@fnal.gov>" \
      fts_rest_version="3.14.3"

#> Add supported Alma9 repos
ADD http://fts-repo.web.cern.ch/fts-repo/fts3-el9.repo \
    http://fts-repo.web.cern.ch/fts-repo/fts3-depend.repo \
#    almalinux-crb.repo \
    /etc/yum.repos.d

#> Update image
#> Install EL9 dependencies
RUN <<EOF
dnf update -y
dnf install -y epel-release \
  https://repo.osg-htc.org/osg/25-main/osg-25-main-el9-release-latest.rpm
dnf clean all
rm -rf /var/cache/dnf
EOF

#> Install FTS and other utils
RUN <<EOF
dnf install -y \
  fts-rest-server-3.14.3 \
  fts-rest-server-selinux-3.14.3 \
  procps which \
  cronie \
  gettext vo-client \
  mariadb
dnf clean all
rm -rf /var/cache/dnf

#> Clear up cronie anacron job
rm -f /etc/cron.d/0hourly \
  /etc/cron.hourly/0anacron

groupmod -g 2000 fts3 2>/dev/null || true
usermod -u 1000 -g 2000 fts3 2>/dev/null || true

EOF

WORKDIR /tmp

#> Install s6-overlay
RUN <<EOF
curl -LO https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
curl -LO https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz
tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
rm -rf /tmp/s6-overlay-*.tar.xz
EOF

#> Ports for FTS3, 8446 for REST
EXPOSE 8446

#> Copy configuration rootfs
COPY rootfs/ /

#> Grant group read and write
RUN <<EOF
#> Grant group write access
chmod -R 775 /etc/grid-security \
  /etc/httpd /run/httpd /var/log/httpd \
  /var/log/fts3rest

#> Grant group read access
chmod 664 /etc/fts3/*
chmod 775 /run /etc/fts3
chmod g=u /etc/passwd

#> Needed for pure k8s environment
chown fts3:root /var/log/fts3rest

#> Ensure all run scripts are executable
chmod +x /etc/s6-overlay/s6-rc.d/*/run
chmod +x /etc/s6-overlay/s6-rc.d/*/up
chmod 0777 /tmp

chmod +x /tmp/setup.sh
EOF

WORKDIR /

ENTRYPOINT ["/init"]
