#> Docker image build arguments:

# Build dummy django rpm
# Fix: python3-django3 no longer exists in almalinux
# EPEL repo. There is minor differences in django 4.2 (LTS)
FROM almalinux:9.8 as django

RUN dnf install -y rpm-build && \
    dnf clean all && \
    rm -rf /var/cache/dnf

ADD django-provide.spec /tmp/django-provide.spec

# Build the RPM
RUN rpmbuild -bb /tmp/django-provide.spec --define "_rpmdir /tmp/dummy-repo" \
         --define "_srcrpmdir /tmp/dummy-repo" \
         --define "_builddir /tmp"

# Main image
FROM almalinux:9.8
ARG VERSION=3.14.2

ARG S6_OVERLAY_VERSION=3.2.2.0

LABEL fts-version=${VERSION}-s6 \
      description="FTS3 Monitoring Container" \
      maintainer="Dennis Lee <dylee@fnal.gov>" \
      fts_monitoring_version="${VERSION}" \
      fts_mysql_version="${VERSION}"

#> Add supported Alma9 repos
ADD http://fts-repo.web.cern.ch/fts-repo/fts3-el9.repo \
    http://fts-repo.web.cern.ch/fts-repo/fts3-depend.repo \
#    almalinux-crb.repo \
    /etc/yum.repos.d

#> Update image
#> Install EL9 dependencies
RUN <<EOF
dnf update -y
dnf install -y epel-release \
  https://repo.osg-htc.org/osg/25-main/osg-25-main-el9-release-latest.rpm
dnf clean all
rm -rf /var/cache/dnf
EOF

COPY --from=django /tmp/dummy-repo/x86_64/django-provide-1.0-1.el9.x86_64.rpm /tmp/

#> Install FTS
RUN <<EOF
dnf install -y \
  python3-django4.2 \
  /tmp/django-provide-1.0-1.el9.x86_64.rpm \
  fts-monitoring-${VERSION} \
  fts-monitoring-selinux-${VERSION} \
  fts-mysql-3.14.2 \
  python3-sqlalchemy \
  procps which \
  gettext vo-client \
  cronie \
  mariadb
dnf clean all
rm -rf /var/cache/dnf

#> Clear up cronie anacron job
rm -f /etc/cron.d/0hourly \
  /etc/cron.hourly/0anacron \
  /tmp/django-provide-1.0-1.el9.x86_64.rpm

groupmod -g 2000 fts3 2>/dev/null || true
usermod -u 1000 -g 2000 fts3 2>/dev/null || true

EOF

WORKDIR /tmp

#> Install s6-overlay
RUN <<EOF
curl -LO https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz
curl -LO https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz
tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz
rm -rf /tmp/s6-overlay-*.tar.xz
EOF

#> Ports for FTS3, 8449 for monitoring
EXPOSE 8449

#> Copy configuration rootfs
COPY rootfs/ /

#> Ensure all run scripts are executable
RUN <<EOF
chmod +x /etc/s6-overlay/s6-rc.d/*/run
chmod +x /etc/s6-overlay/s6-rc.d/*/up
chmod 0777 /tmp
#> setup script permissions
chmod +x /tmp/setup.sh
EOF

WORKDIR /

ENTRYPOINT ["/init"]
