name: Build fnal-fts3
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
     - "test-build-fts3"
    tags:
     - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build fts3 image
        uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: build
        with:
          image: fnal-fife/fnal-fts3-rubin
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/fts3/Containerfile
          context: docker/fts3/.
          push: true
          platforms: linux/amd64
          additional-tags: '${{ github.event.ref }}'
